application:
  title: "An example Spring Boot app using Java"

server:
  http:
    port: 8080
  compression:
    enabled: true
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit

logging:
  file: logs/springboot-java-example.log


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
