application:
  name: "spring-boot-java-example"
  description: "An example Spring Boot app using Java"

server:
  http:
    port: 8080
  compression:
    enabled: true
  port: 8443
  ssl:
    enabled: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
logging:
  file:
    name: logs/spring-boot-java-example.log